micronaut:
  application:
    name: micronaut-kafka-kubernetes
---
mongodb:
  uri: mongodb://adminuser:password123@${MONGO_HOST:localhost}:${MONGO_PORT:64479}/authSource=auth-source
---
db:
  name: 'fruit'
  collection: 'fruit'

